name: Mac Build
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneOSX
      - run: |
          cd build/StandaloneOSX
          mv StandaloneOSX.app "Fusion Helper.app"
          zip -r FusionHelper_Mac.zip "Fusion Helper.app"
      - uses: softprops/action-gh-release@v2
        with:
          files: build/StandaloneOSX/FusionHelper_Mac.zip
          fail_on_unmatched_files: true
